services:
    web:
        image: nginx:alpine
        ports:
            - 8080:80
        volumes:
            - ./src:/src
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php

    php:
        build: .
        volumes:
            - ./src:/src
            - ./php.ini:/usr/local/etc/php/php.ini
        ports:
            - 9000:9000
        depends_on:
            - mysql

    mysql:
        image: mysql:latest
        command: --default-authentication-plugin=mysql_native_password
        ports:
            - 3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: supersafepassword
